implementation of lesson 17
max-x444/nix pull request #7
Opened 2022-08-02 21:58 UTC by max-x444

2022-08-02 21:59 UTC, max-x444 commented
![](https://github.trello.services/images/mini-trello-icon.png) [IO/NIO](https://trello.com/c/b8OeeXqV/87-io-nio)

2022-08-04 20:30 UTC, Fabolo12 requested changes

2022-08-04 20:30 UTC, Fabolo12 commented on project/src/main/java/com/Main.java
> +            + File.separator + "resources" + File.separator + "xml";
Чтение из ресурсов не верное

2022-08-04 20:30 UTC, Fabolo12 commented on project/src/main/resources/json
> +[
файл должен иметь название {text}.json

2022-08-04 20:30 UTC, Fabolo12 commented on project/src/main/resources/xml
> +<?xml version="1.0"?>
файл должен иметь название {text}.xml

2022-08-05 21:59 UTC, merged