implementation of lesson 18
max-x444/nix pull request #8
Opened 2022-08-03 14:01 UTC by max-x444

2022-08-03 14:11 UTC, max-x444 commented
![](https://github.trello.services/images/mini-trello-icon.png) [SOLID](https://trello.com/c/yQhqHpYq/93-solid)

2022-08-04 20:36 UTC, Fabolo12 requested changes

2022-08-04 20:36 UTC, Fabolo12 commented on solid/src/main/java/com/example/model/Amount.java
> +public interface Amount {
Это уже лишнее, тут обычный геттер

2022-08-04 20:36 UTC, Fabolo12 commented on solid/src/main/java/com/example/model/ProductBundle.java
> +public class ProductBundle extends NotifiableProduct implements Amount {
нет изменений конструктора

2022-08-04 20:36 UTC, Fabolo12 commented on solid/src/main/java/com/example/utils/ProductUtils.java
> +        List<NotifiableProduct> products = repository.getAll().stream()
Репозиторий не должен возвращать все, чтоб потом не делать каст

2022-08-05 20:47 UTC, Fabolo12 approved these changes

2022-08-05 21:59 UTC, merged